name: 'LeanIX Integration API Default Config Action'
description: 'Provisions a default configuration into the Integration API of all regions.'
inputs:
  default_config_file:
    description: 'The location of the file that contains the default configuration that is used as the input for this action.'
    required: true
    default: 'integration-api-default-config.json'
  environment:
    description: 'The environment to provision to, e.g. test or prod'
    required: true
    default: 'test'
  region:
    description: 'The region to provision to, e.g. westeurope or australiaeast. Leave empty to provision to all regions.'
    required: false
runs:
  using: 'docker'
  image: 'docker://leanixacrpublic.azurecr.io/integration-api-default-config-action:latest'