name: test

on: 
  push:
    branches:
      - feature/**
    paths-ignore:
      - 'README.md'
      - 'test/**'
  workflow_dispatch:

jobs:
  test:
    name: test-${{ github.run_number }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get credentials
      uses: leanix/secrets-action@master
      with:
        secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

    - name: Provision default config
      uses: ./
      with:
        default_config_file: 'test/integration-api-default-config.json'
        environment: 'test'